### PR TITLE
Versioncheck

### PR DESCRIPTION
**Pull request by raymondnijssen**
Function for getting local or repo version of the plugin. And function for generating a message if there's a new plugin. Should not report anything in case you are offline.

Uses standard python modules:
urllib
configparser

### CODE REVIEW

**Comment by arongergely** [comment]
Thank you! Looks good, I will test. 
Will just have to keep in mind not to bump the version number in metadata.txt in master without actually making a new release

**Comment by raymondnijssen** [comment]
Yes, I thought about that. But normally you change the metadata.txt only when releasing, right? I could not change of anything else except for making a separate file somewhere, holding the version number. Or, even worse, download the entire repo as a zip and scan it for release files.

**Comment by arongergely** [comment]
Yes I would only change it in master if i would be about to make a release so I think its OK. 
I will probably mention this release 'workflow' in the README for the development setup.

I did start to  edit version numbers locally though when making test versions - i thought its good to keep track test plugins versios can easily get mixed up, there are multiple people helping to test too, etc. 

So I input `1.0.2rc1` (release candidate 1) locally, generated the plugin and shared that with a few people for testing. Then i collect feedback + even feauture requests and then release 1.0.2.rc2, have it tested, before making a final release

Now thinking along that other neat idea of yours, I could check if the version has any suffixes like release candidate X.X.X.rc1, and others and let the user know that this is a test version and not for production.

**Comment by raymondnijssen** [comment]
Yes, you can make the nuber check fancy pancy after all. You can also use point releases for testing and always do minors for real releases.

**Comment by arongergely** [comment]
Thanks @raymondnijssen! ;)

**Pull request merged**
